config/routes.rb
Rails.application.routes.draw do
  resources :entries, param: :entry_id
  resources :users, param: :user_id, except: %i(index) do
    member do
      get :following_entries
    end
  end
  resource :session, only: %i(new create destroy)
  resources :comments, param: :comment_id, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
  resources :admins, only: :index

  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  scope :latest, ->{order created_at: :desc}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save {email.downcase!}

  has_many :entries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  has_secure_password

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  def following_entries
    Entry.where user_id: following_ids
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_administrator

  def index
    users = User.all
    entries = Entry.latest
    comments = Comment.all
    @manageables = [] << users << entries << comments
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  attr_reader :comment

  before_action :find_comment, :authenticate_administrator, only: :destroy

  def create
    @comment = Comment.new comment_params
    comment.save
    redirect_back fallback_location: root_path
  end

  def destroy
    comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit :content, :user_id, :entry_id
  end

  def find_comment
    @comment = Comment.find_by id: params[:comment_id]
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  attr_reader :entry

  before_action :authenticate_user, only: %i(new create destroy)
  before_action :find_entry, only: %i(show destroy)
  before_action :authenticate_administrator, only: :destroy

  def index
    if params[:page] == "0" || params[:page] == "1" || params[:page] == nil
      page = 0
    else
      page = params[:page]
    end
    @entries = Entry.latest.limit(5)
      .offset((page.to_i > 1 ? page.to_i - 1 : page.to_i) * 5)
    total_entries = Entry.all.size
    @total_pages = total_entries % 5 == 0 ? total_entries / 5 : total_entries / 5 + 1
  end

  def show
    @comment = entry.comments.build
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = current_user.entries.build entry_params
    if entry.save
      flash[:success] = "Entry created successfully!"
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    entry.destroy
    redirect_back fallback_location: root_path
  end

  private

  def entry_params
    params.require(:entry).permit :title, :body
  end

  def find_entry
    @entry = Entry.find_by id: params[:entry_id]
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find params[:followed_id]
    current_user.follow user
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow user
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Logged in successfully!"
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_reader :user

  before_action :find_user, only: %i(show destroy)
  before_action :authenticate_administrator, only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if user.save
      log_in user
      flash[:success] = "You have signed up successfully!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    if params[:page] == "0" || params[:page] == "1" || params[:page] == nil
      page = 0
    else
      page = params[:page]
    end
    @user_entries = user.entries.latest.limit(5)
      .offset((page.to_i > 1 ? page.to_i - 1 : page.to_i) * 5)
    total_entries = user.entries.size
    @user_entries_pages = total_entries % 5 == 0 ? total_entries / 5 : total_entries / 5 + 1
  end

  def following_entries
    if params[:page] == "0" || params[:page] == "1" || params[:page] == nil
      page = 0
    else
      page = params[:page]
    end
    @entries = current_user.following_entries.latest.limit(5)
      .offset((page.to_i > 1 ? page.to_i - 1 : page.to_i) * 5)
    total_entries = current_user.following_entries.size
    @total_pages = total_entries % 5 == 0 ? total_entries / 5 : total_entries / 5 + 1
    render "entries/index"
  end

  def destroy
    user.destroy
    redirect_back fallback_location: root_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user ? true : false
  end

  def current_user? user
    user == current_user
  end

  def entry_commentable? entry
    current_user.following?(entry.user) || current_user == entry.user
  end

  def authenticate_administrator
    return true if current_user&.admin?
    flash[:error] = "You don't have permission for this action!"
    redirect_to root_path
  end

  def authenticate_user
    return true if logged_in?
    flash[:error] = "You need to sign in first!"
    redirect_to root_path
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def paginate total_pages
    return unless total_pages > 1
    paginate_element = content_tag :div, ""

    total_pages.times do |page|
      paginate_element << link_to(page + 1, "#{request.path}?page=#{page + 1}")
    end

    paginate_element
  end
end

app/views/admins/index.html.erb
<% @manageables.each do |manageable| %>
  <% next if manageable.empty? %>
  <div class="manageable_column">
    <h3>List of all <%= manageable.first.class.to_s.downcase %></h3>
    <%= render manageable %>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<b><%= link_to comment.user.name, comment.user %></b>
<i>
  commented on <b><%= comment.created_at.strftime "%m/%d/%y" %></b> at
  <b><%= comment.created_at.strftime "%H:%M" %></b>

  <% if current_user&.admin? %>
    <b><%= link_to "Delete", comment, method: :delete,
      data: {confirm: "Are you sure?"} %></b>
  <% end %>
</i><br>

<%= comment.content %><br>

app/views/entries/_entry.html.erb
<span>
  <b><%= link_to entry.title, entry %></b> by
  <%= link_to entry.user.name, entry.user %>
</span>

<% if current_user&.admin? %>
  <b><%= link_to "Delete", entry, method: :delete,
    data: {confirm: "Are you sure?"} %></b>
<% end %><br>

<span><%= entry.body %></span><br>
<i>Posted on <b><%= entry.created_at.strftime "%m/%d/%y" %></b> at
  <b><%= entry.created_at.strftime "%H:%M" %></b></i><br><hr>

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/entries/index.html.erb
<div>
  <% if @entries.any? %>
    <h3>Latest entries</h3>
    <div><%= render @entries %></div>
    <%= paginate @total_pages %>
  <% else %>
    <h3>There is no entries in this page yet!</h3>
  <% end %>
</div>

app/views/entries/new.html.erb
<%= form_for @entry do |f| %>
  <%= render "shared/error_messages", resource: @entry %>

  <%= f.text_field :title, placeholder: "Entry's title..." %><br>
  <%= f.text_area :body, placeholder: "Entry's body..." %>
  <%= f.submit "Post" %>
<% end %>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
Author: <b><%= link_to @entry.user.name, @entry.user %></b><br>
<i>Posted on: <b><%= @entry.created_at.strftime "%m/%d/%y" %></b> at
  <b><%= @entry.created_at.strftime "%H:%M" %></b></i><br>
<p><%= @entry.body %></p>

<h4>Comments:</h4>

<%= render @entry.comments.reject &:new_record? %>

<% if logged_in? && entry_commentable?(@entry) %>
  <%= form_for @comment do |f| %>
    <%= f.text_field :content, placeholder: "Comment...", autofocus: true,
      autocomplete: :off %>
    <%= hidden_field_tag "comment[user_id]", current_user.id %>
    <%= hidden_field_tag "comment[entry_id]", @entry.id %>

    <%= f.submit "Comment" %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Homepage", root_path %>
<% if logged_in? %>
  <% if current_user&.admin? %>
    <%= link_to "Admin page", admins_path %>
  <% end %>
  <%= link_to "My following entries", following_entries_user_path(user_id: current_user.id) %>
  <%= link_to "Create new entry", new_entry_path %>
  <%= link_to "Log out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Log in", new_session_path %>
<% end %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    The form contains <%= pluralize resource.errors.count, "error" %>.
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user? user %>
  <div id="follow_form">
    <% if current_user.following? user %>
      <%= render "unfollow", user: user %>
    <% else %>
      <%= render "follow", user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: user.id),
  html: {method: :delete} do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/_user.html.erb
<p>
  <%= link_to "#{user.name} - #{user.email}", user %>
  <% if current_user&.admin? %>
    <b><%= link_to "Delete", user, method: :delete,
      data: {confirm: "Are you sure?"} %></b>
  <% end %>
</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <%= render "shared/error_messages", resource: @user %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="user_info">
  <h2>Name: <%= @user.name %></h2>
  <h3>Email: <%= @user.email %></h3>
  <%= render "follow_form", user: @user if logged_in? %>
</div>
<div class="user_entries">
  <% if @user.entries.any? %>
    <h3>Latest entries</h3>
    <div><%= render @user_entries %></div>
    <%= paginate @user_entries_pages %>
  <% else %>
    <h3>This user doesn't have any entries yet!</h3>
  <% end %>
</div>